Cart/urls.py
from django.urls import path

from Cart.views import add_to_cart, delete_cart, show_cart
from Cart.api.api import Cart

app_name="Cart"

urlpatterns = [
    path("add-to-cart",add_to_cart,name="add-to-cart"),
    path("show-cart",show_cart,name="show-cart"),
    path("delete-cart/<str:detect>",delete_cart,name="delete-cart"),
    
    path("api-cart",Cart.as_view() ,name="show-cart-api"),
    
   


]

Payment/urls.py
from django.urls import path
from .views import payment_start,payment_return,show_factors

app_name="Payment"
urlpatterns = [

    path('payment-start/<int:amount>', payment_start, name="payment_start"),
    path('payment-return/', payment_return, name="payment_return"),
    path("showfactor",show_factors,name="showfactor"),
]

Product/urls.py
from django.urls import path

from Product.Api.Product_api import  ProductDetailView, ProductListView,CategoryDetailView
from .views import ProductDetail, Show_wishList,ShowProduct, add_to_wishlist, delete_from_wishlist

app_name="Product"
urlpatterns = [
    path('detailproduct/<int:product_id>',ProductDetail.as_view(),name="detailproduct"),
    path('show-product-by-category/',ShowProduct.as_view(),name="showproduct"),
    path("add-wishlist/", add_to_wishlist, name="add_wishlist"),
    path("del-wishlist/<int:id>", delete_from_wishlist, name="delete_wishlist"),
    path("show-wishlist/", Show_wishList.as_view(), name="Show_wishList"),

   #API PATH
  
    path('apiproduct-list/', ProductListView.as_view(), name='product_list'),
    path('apiproduct-detail/<str:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('categorydetail/<int:pk>',CategoryDetailView.as_view(),name='category_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include , re_path
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views


from rest_framework.routers import DefaultRouter


from Comment.Api.Comment_Api import CommentView
from .views import Home, searchbox
from Product.Api.Product_api import CategoryListViewSet
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)




router = DefaultRouter()

router.register(r'categorylist', CategoryListViewSet, basename='categorylist'),
# router.register(r'CommentView', CommentView, basename='CommentView')
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/',searchbox, name='serachbox'),
    path('' , Home.as_view() ,  name='home'),
    path('comment/',include('Comment.urls', namespace='comment')),
    path('product/',include("Product.urls",namespace="product") ),
    path("user/", include("User.urls", namespace='user')),
    path('payment/', include("Payment.urls",namespace="payment")),
    path('cart/', include("Cart.urls",namespace="cart")),
    # path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]+router.urls   



#1651374
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
# pylint: disable=line-too-long
from django.db import models
from User.models import Customer, Profile, SalesMan
from Product.models import Product
from django.utils.translation import gettext as _



class CartMe(models.Model):
    user=models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='CartmetoCustomer',help_text="نام کاربری")
    product=models.ManyToManyField(Product,through="CartItem",help_text="کالاها")
    priceTotla=models.PositiveIntegerField(verbose_name=_("priceTotla"),null=True,blank=True)
    discount=models.CharField(max_length=10,verbose_name=_("discount"),null=True,blank=True)
    date=models.DateTimeField(auto_now=True)
    ispaid=models.BooleanField(default=False)

    class Meta:
        verbose_name="Cart"
        verbose_name_plural="Carts"
    
    def __str__(self) -> str:
        return self.profile.username




class CartItem(models.Model):
    cart=models.ForeignKey(CartMe,on_delete=models.CASCADE,related_name='CartItemtoCartMe',help_text="سبد خرید")
    product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name='CartItemtoProduct',help_text="کالاها")
    salesman=models.ForeignKey(SalesMan,null=True,blank=True,on_delete=models.DO_NOTHING, related_name='cartitemtosels')
    class Meta:
        verbose_name="Product"
        verbose_name_plural="Products"




class History(models.Model):
    customer=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='HistorytoCustomer',help_text="مشتری")
    date=models.DateTimeField(auto_now_add=True)
    date_update=models.DateTimeField(auto_now=True)
    factor=models.JSONField(null=True,blank=True,verbose_name=_("factor"),help_text="فاکتور خرید")


    class Meta:
        verbose_name="History"
        verbose_name_plural="Historys"
    
    def __str__(self) -> str:
        return self.customer.email

    

Cart/views.py
import json
from charset_normalizer import detect

from django.http import HttpResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.core.cache import caches

from Product.models import Product
from .utils import add_cart,show_cart_utils

def add_to_cart(request):
    detect = request.POST.get("name","")+request.POST.get("color","")+request.POST.get("سایزلباس","")
    if (int(request.POST.get("amount")) - int(request.POST.get("count"))) >= 0:
        if not request.user.is_authenticated:
            if not request.session.session_key:
                request.session.save()
            add_cart(request,request.session.session_key,detect)
            return redirect("product:detailproduct",request.POST.get("id"))
        else:
            add_cart(request,request.user.email,detect)
            return redirect("product:detailproduct",request.POST.get("id"))

    else:
        return HttpResponse("tedad kafi nist ")


def show_cart(request):

    if not request.user.is_authenticated:

        ctx=show_cart_utils(request,request.session.session_key)
        return render(request,"Cart/cart.html",ctx)
        
    else:
        ctx=show_cart_utils(request,request.user.email)
        return render(request,"Cart/cart.html",ctx)



def delete_cart(request,detect):
    redis_cache=caches['default']
    cart=redis_cache.client.get_client()
    if not request.user.is_authenticated:
        cart.hdel(request.session.session_key,detect)
        return redirect("cart:show-cart")
    else:
        cart.hdel(request.user.email,detect)
        return redirect("cart:show-cart")

Cart/templates/Cart/cart.html
{% extends 'home.html' %}
{% load static %}   

{% block main %}

<!-- Breadcumbs start -->
<div class="e-breadcumb-wrap text-center">
    <h2 class="e-breadcumb-title">سبد خرید </h2>
    <ul class="e-breadcumb-kist">
        <li>
            <a href="{% url 'home' %}">خانه </a>
        </li>
        <li>
            <a href=''> صفحات </a>
        </li>
        <li>
            <a href=''>سبد خرید  </a>
        </li>
    </ul>
</div>
<!-- Product Category start -->
<section class="e-shopcart-wrap">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 col-lg-12">
                <div class="e-shopcart-sec">                    
                    <div class="shopcart-table-wrap mb-30">
                        <form class="table-responsive">
                            <table class="shopcart-table">
                                <thead>
                                  <tr>
                                    <th>محصول </th>
                                    <th>رنگ</th>
                                    <th>تعداد </th>
                                    <th>موجودی </th>
                                    <th>قیمت </th>
                                    <th>قیمت جمع </th>
                                    <th>&nbsp;</th>
                                  </tr>
                                </thead>
                                <tbody>
                                    {% for key,elm in show.items %}
                  
                                  <tr>
                                    <td>
                                        <div class="sc-productwrap">
                                            <a href="" class="sc-product-thumb">
                                                
                                                <img src='{{elm.img}}' alt="محصول" class="img-fluid">
                                                
                                            </a>
                                            <div class="sc-product-details">
                                                <a href="{% url 'product:detailproduct' elm.id %}" class="sc-product-ttl">{{elm.name}}</a>
                                                {% if elm.سایزلباس %}
                                                <p class="sc-product-sz">اندازه: {{elm.سایزلباس}} </p>
                                                {% endif %}
                                                
                                            </div>
                                        </div>      
                                    </td>
                                    <td>
                                        <div>
                                            {% if elm.color %}
                                            <h6>{{elm.color}}</h6>
                                            {% else %}
                                            <h5>-</h5>
                                            {% endif %}

                                        </div>

                                    </td>
                                    <td> 
                                        <div >
                                            <h6 class="quantity">{{elm.count}}</h6>
                                            {% comment %} <input type="text" class="quantity" value="{{elm.count}}">{% endcomment %}
                                            {% comment %} <span class="quantity-minus pa-sub quantity-icon"> - </span>                                                
                                            <span class="quantity-plus  pa-add quantity-icon"> + </span> {% endcomment %} 
                                        </div>
                                    </td>
                                    {% if elm.status %}
                                    <td><span class="sc-product-prc">موجود است</span> </td>
                                    <td><span class="sc-product-prc">{{elm.price}} تومان</span></td> 
                                    <td><span class="sc-product-prc">{{elm.price_total}}</span></td>
                                    {% else %}
                                    <td><span class="sc-product-prc">موجود نیست</span> </td>
                                    <td><span class="sc-product-prc">-</span></td> 
                                    <td><span class="sc-product-prc">-</span></td>
                                    {% endif %}
                                    <td>
                                        <a href='{% url "cart:delete-cart" elm.detect %}' class="sc-produc-remove e-remove-product">
                                            <img src='{% static "assets/images/index1/svg/cut.svg"%}' alt="icon">
                                        </a>
                                    </td>
                                  </tr>                                                                  
                                  {% endfor %}
                                     
                                </tbody>
                              </table>
                        </form>
                    </div>
                    <div class="shopcart-bottom mb-30">
                        <ul class="shopcart-dis-list">
 
                            <li>                                
                                <a href='' class="e-btn black update-cart">بروز رسانی سبد </a>
                            </li>
                        </ul>
                    </div> 
                </div>                      
            </div>            
            <div class="col-xl-3 col-lg-12">
                <div class="e-shopcart-sidebar">
                    <div class="e-totalsumry mb-30">
                        <div class="e-totalsumry-header">
                            <h2 class="e-totalsumry-ttl">خلاصه مجموع سبد خرید</h2>
                        </div>
                        <div class="e-totalsumry-body">
                            <ul class="e-totalsumry-list">
                                <li>
                                    <span class="ts-list-head">مجموع سبد:</span>
                                    <span class="ts-list-shead">{{price_total}} تومان</span>
                                </li>
                               <li>
                                    <span class="ts-list-head">حمل و نقل: </span>
                                    <span class="ts-list-shead">- تومان</span>
                                </li>
                            </ul>
                            <!-- <a href='{%static "javascript:void(0);" %}' class="ts-chngadd">Change Address
                                <img src='{% static "assets/images/index1/svg/edit.svg"%}' alt="edit">
                            </a> -->
                        </div>  
                        <div class="e-totalsumry-fotr">
                            <ul class="e-totalsumry-list total">
                                <li>
                                    <span class="ts-list-head">گراند توتال</span>
                                    <span class="ts-list-shead">{{price_total}} تومان</span>
                                </li>
                            </ul>
                        </div>  
                    </div> 
                    <a href="{% url 'payment:payment_start' price_total %}" class="e-btn">پرداخت صورتحساب </a>
                </div>                      
            </div>            
        </div>
    </div>
</section>
{% endblock main %}