Cart/urls.py
from django.urls import path

from Cart.views import add_to_cart, delete_cart, show_cart
from Cart.api.api import Cart

app_name="Cart"

urlpatterns = [
    path("add-to-cart",add_to_cart,name="add-to-cart"),
    path("show-cart",show_cart,name="show-cart"),
    path("delete-cart/<str:detect>",delete_cart,name="delete-cart"),
    
    path("api-cart",Cart.as_view() ,name="show-cart-api"),
    
   


]

User/urls.py
from django.urls import path

from .views import forget_password, login, logout, register, activate,forget_pass, show_profile,user_session_logedin ,set_true
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .views import *
from User.api.views import Login_api,logout_api,RegisterView


app_name="User"

urlpatterns = [
#----------------restless url----------------------
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("register/", register, name="register"),
    path("activate/<str:valid>", activate, name="activate"),
    path("forget_password/", forget_password, name="forget_password"),
    path("forget_pass/", forget_pass, name="forget_pass"),
    path("set_true/<str:auten>", set_true, name="set_true"),
    path('profile/<int:id>',show_profile.as_view(),name="profile"),
#----------------linked divice---------------
    path("linked_dev/", user_session_logedin, name="user_session"),
    path('profile/<int:id>',show_profile.as_view(), name='profile'),
    path('set_true/<str:auten>',set_true, name='set_true'),
    
    

#---------------API-----------------------
    path("api/login/",Login_api.as_view(), name="api-login"),
    path("api/register",RegisterView.as_view()),
    path("api/logout",logout_api),
#--------------jwt token---------------------
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),


]

project/urls.py
from django.contrib import admin
from django.urls import path,include , re_path
from django.conf import settings
from django.conf.urls.static import static
from azbankgateways.urls import az_bank_gateways_urls
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views


from rest_framework.routers import DefaultRouter


from Comment.Api.Comment_Api import CommentView
from .views import Home, searchbox
from Product.Api.Product_api import CategoryListViewSet
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)




router = DefaultRouter()

router.register(r'categorylist', CategoryListViewSet, basename='categorylist'),
# router.register(r'CommentView', CommentView, basename='CommentView')
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/',searchbox, name='serachbox'),
    path('' , Home.as_view() ,  name='home'),
    path('comment/',include('Comment.urls', namespace='comment')),
    path('product/',include("Product.urls",namespace="product") ),
    path("user/", include("User.urls", namespace='user')),
    path('payment/', include("Payment.urls",namespace="payment")),
    path('cart/', include("Cart.urls",namespace="cart")),
    # path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]+router.urls   



#1651374
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/forms.py
from django import forms
from django.contrib.auth import get_user_model,password_validation
from django.forms import ValidationError, TextInput, EmailInput, PasswordInput
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator

from User.models import Customer,Profile



User = get_user_model()



class RegisterForm(forms.ModelForm):
    re_password = forms.CharField(widget=PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را تکرار نمایید', 'type':'password', 'required':'', 'class':'e-field-inner'}),label='تکرار رمزعبور')
    
    class Meta:
        model = Profile
        fields = ['first_name',"last_name",'email','password',"re_password","address","postal_code"]

        widgets = {
            'first_name': TextInput(attrs={"background-color":"red",'placeholder': 'لطفا نام  خود را وارد نمایید', 'type':'text', 'required':'', 'class':'e-field-inner'}),
            'last_name': TextInput(attrs={'placeholder': 'لطفا نام خانوادگی خود را وارد نمایید', 'type':'text', 'required':'', 'class':'e-field-inner'}),
            'email': EmailInput(attrs={'placeholder': 'لطفا ایمیل خود را وارد نمایید', 'type':'email', 'required':'', 'class':'e-field-inner'}),
            'password': PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید', 'type':'password', 'required':'', 'class':'e-field-inner', "id":"password"}),
            'address': TextInput(attrs={'placeholder': 'لطفا ادرس خود را وارد نمایید', 'type':'text', 'required':'', 'class':'e-field-inner'}),
            'postal_code':TextInput(attrs={'placeholder': 'لطفا کدپستی خود را وارد نمایید', 'type':'text', 'required':'', 'class':'e-field-inner'}),
        }
        labels = {
            'first_name' : _('نام'),
            'last_name' : _('نام خانوادگی'),
            'email' : _('ایمیل'),
            'password' : _('رمزعبور'),
            're_password' :'تکرار رمزعبور',
            'address' : _('ادرس'),
            'postal_code': _('کدپستی')
        }
        validators = {
            'email' : EmailValidator('ایمیل وارد شده معتبر نمیباشد')
        }
    

    def clean_email(self):
        email = self.cleaned_data.get('email')
        is_exists_user_by_email = User.objects.filter(email=email).exists()
        if is_exists_user_by_email:
            raise forms.ValidationError('ایمیل وارد شده تکراری میباشد')
        return email


    def clean_password(self):

        try:
            password_validation.validate_password(self.cleaned_data.get("password"), self.instance)
            return self.cleaned_data.get("password") 
        except ValidationError as error:
            raise forms.ValidationError("""
                                        1-این پسورد خیلی کوتاه است حداقل 8 کاراکتر
                                        2-پسورد خیلی ساده است
                                        3-پسورد فقط عدد است
                                        """)
    def clean_re_password(self):
        password = self.cleaned_data.get('password')
        re_password = self.cleaned_data.get('re_password')

        

        if password != re_password:
            raise forms.ValidationError('کلمه های عبور مغایرت دارند')

        return password




    def save(self, commit: bool = ...) :
        self.instance.set_password(self.cleaned_data.get("password"))
        return super().save(commit=commit)


class LoginForm(forms.Form):
        email=forms.EmailField(widget=EmailInput(attrs={'placeholder': 'لطفا ایمیل خود را وارد نمایید', 'type':'email', 'required':'', 'class':'e-field-inner'}),label='ایمیل')
        password=forms.CharField(max_length=16,widget=PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید', 'type':'password', 'required':'', 'class':'e-field-inner'}),label='رمزعبور')
        fields = ['email','password']
        labels = {
            'email' : 'ایمیل',
            'password' : 'کلمه عبور',
        }



class ForgetPasswordForm(forms.Form):
            email=forms.EmailField(widget=EmailInput(attrs={'placeholder': 'لطفا ایمیل خود را وارد نمایید', 'type':'email', 'required':'', 'class':'e-field-inner'}),label='ایمیل  ')
            fields = ['email']
            labels = {
                'email' : _('ایمیل'),
            }



class ForgetPassForm(forms.Form):
        password=forms.CharField(max_length=16,widget=PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید', 'type':'password', 'required':'', 'class':'e-field-inner'}),label=' رمزعبور')
        re_password = forms.CharField(widget=PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را تکرار نمایید', 'type':'password', 'required':'', 'class':'e-field-inner'}),label='تکرار رمزعبور')
        fields = ['password',"re_password"]
        widgets = {
            'password': PasswordInput(attrs={'placeholder': 'لطفا کلمه عبور خود را وارد نمایید', 'type':'password', 'required':'', 'class':'e-field-inner', "id":"password"}),
        }
        labels = {
            'password' : _('رمزعبور'),
            're_password' :'تکرار رمزعبور',
        }
        validators = {
        }



        def clean_re_password(self):
            password = self.cleaned_data.get('password')
            re_password = self.cleaned_data.get('re_password')


            if password != re_password:
                raise forms.ValidationError('کلمه های عبور مغایرت دارند')
            return password


        def save(self, commit: bool = ...) :
            self.instance.set_password(self.cleaned_data.get("password"))
            return super().save(commit=commit)

User/api/views.py
from django.contrib.auth import login as _login , authenticate,logout


from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import generics
from rest_framework_simplejwt.views import TokenObtainPairView


from urllib import response
from pytz import timezone


from User.models import Profile
from User.api.serialaizer import LoginSerializer,RegisterSerializer



#---------------------------------------------APIregister------------------------------
class RegisterView(generics.CreateAPIView):
 
    queryset = Profile.objects.all()
    # permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer


#--------------------------------------------APIlogin-----------------------------------
class Login_api(TokenObtainPairView):

    def post(self,request):
        serialaizer = LoginSerializer(data=request.data)
        
        if serialaizer.is_valid():
            email=serialaizer.validated_data["email"]
            password=serialaizer.validated_data["password"]
            user=authenticate(email=email,password=password)
            if user:
                _login(request,user)
                return Response(serialaizer.data,status=status.HTTP_202_ACCEPTED)
            else:
                return response(serialaizer.data,status=status.HTTP_404_NOT_FOUND)



@api_view(["GET"])
# @permission_classes([IsAuthenticated])
def logout_api(request):
    logout(request)
    return Response('User Logged out successfully')

User/views.py
from django.contrib.auth import authenticate, logout as _logout, login as _login,get_user_model
from django.core.cache import cache


from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.core.cache import cache
from User.utils import linked_devices
from project import settings
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.core.cache import caches


from User.forms import ForgetPassForm, ForgetPasswordForm, RegisterForm ,LoginForm
from .models import Address, Customer, Profile, UserDevice
from .utils import Send_email,make_session
from .tasks import my_validate


from User.forms import ForgetPassForm, ForgetPasswordForm, RegisterForm ,LoginForm
from .models import Address, Customer, Profile, UserDevice
from .utils import filling_cart



User = get_user_model()

@require_http_methods(["GET", "POST"])
def login(request):
    login_form = LoginForm(request.POST or None)
    if request.method == "GET":
        next = request.GET.get("next", "")
        
        if next:
            return render(request, 'User/login_page.html', {'login_form': login_form,'next':next})
        else:
            return render(request, 'User/login_page.html', {'login_form': login_form,})
            
    else:
        if login_form.is_valid():
            email = request.POST.get("email", "")
            password = request.POST.get("password", "")
            user = authenticate(request, email=email, password=password)
            if user is not None:  
                _login(request, user)
                next = request.GET.get("next", "")
                linked_devices(request,user)
                filling_cart(request)
                if next:
                    return redirect(next)
                return redirect('home')
            else:
                 return render(request, 'User/login_page.html', {'login_form': login_form})
        else:
            return render(request, 'User/login_page.html', {'login_form': login_form})


def logout(request):
    _logout(request)
    return redirect('home')


def register(request):
    register_form = RegisterForm(request.POST or None)
    if request.method == "GET":
        return render(request, 'User/register_page.html', {'register_form': register_form})
    elif request.method == "POST":
        if register_form.is_valid():
            user=register_form.save(commit=False)
            user.is_active = False
            user.save()
            cus=Customer.objects.create(profile=user)
            address=Address(add=register_form.cleaned_data.get("address"),postalcode=register_form.cleaned_data.get("postal_code"))
            address.save()
            cus.add.add(address)
            cus.save() 
            opt="activate"
            to_email = register_form.cleaned_data.get('email')
            my_validate.delay(request,to_email,opt)    
            return redirect('user:login')
        else:
            return render(request, 'User/register_page.html', {'register_form': register_form})


def activate(request, valid, backend='django.contrib.auth.backends.ModelBackend'):
    user=Profile.objects.get(email=request.session.get("email"))
    ucode=cache.get(request.session.get("email"))
    if request.session.get("uid")==ucode:
        user.is_active=True
        user.save()
        _login(request,user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect("home")
    else:
        return redirect("user:register")



def forget_password(request):
    forget_password_form = ForgetPasswordForm(request.POST or None)
    if request.method == "GET":
        return render(request, 'User/forget_password.html', {'forget_password_form': forget_password_form})
    else:     
        if forget_password_form.is_valid():
            miss_email=forget_password_form.cleaned_data.get('email')
            user = User.objects.get(email=miss_email)
            if user:
                opt = "forget-pass"
                to_email = forget_password_form.cleaned_data.get('email')
                uid=make_session(request,to_email)
                my_validate.delay(to_email,uid,opt)
                return render(request,'User/forget_status.html',{'status':"please check your email for continue."})
            else:
                return redirect('user:forget_password')



def set_true(request,auten):
    user=Profile.objects.get(email=request.session.get("email"))
    ucode=cache.get(request.session.get("email"))
    if request.session.get("uid")==ucode:
        cache.set("forget",1,300)
        return redirect('user:forget_pass')
        
    else:
        return render(request,"User/forget_password.html")

        

def forget_pass(request):
    forget_pass_form = ForgetPassForm(request.POST or None)
    if request.method == "GET":
        return render(request, 'User/forget_pass.html', {'forget_pass_form': forget_pass_form})
    else:
        user=Profile.objects.get(email=request.session.get("email"))
        ucode=cache.get(request.session.get("email"))
        if request.session.get("uid")==ucode:
                forg=cache.get("forget")
                if forg:
                    if forget_pass_form.is_valid():
                        password = request.POST.get("password", "")
                        user.set_password(password)
                        user.save()
                        user = authenticate(request, email=request.session.get("email"), password=password)
                        _login(request,user)
                        return redirect("home")
                    else:
                        return render(request,"User/forget_pass.html")
                else:
                    return render(request, "User/forget_pass.html")
        else:
            return render(request,"User/forget_password.html")


# @login_required
class show_profile(DetailView):
    model=Profile
    template_name="User/profile.html"
    context_object_name="profile_item"
    pk_url_kwarg="id"






def user_session_logedin(request):
     if request.method == "GET":
        linked_devices(request,request.user)
        linked_devicesies = UserDevice.objects.filter(user=request.user)
        ctx={
            'linked_devices':linked_devicesies
        }
        return render(request,'session.html',ctx)

def delet_session(request):
    pass

User/templates/User/forget_pass.html
{% extends 'home.html' %}
{%load static %}

{% block main %}
<!-- Breadcumbs start -->
<div class="e-breadcumb-wrap text-center">
    <h2 class="e-breadcumb-title">ورود به حساب کاربری</h2>
    <ul class="e-breadcumb-kist">
        <li>
            <a href="{% url 'home' %}">خانه </a>
        </li>
        <li>
            <a href='{%static "javascript:void(0);" %}'> ورود به حساب کاربری</a>
        </li>
    </ul>
</div>
<!-- Product Category start -->
<div class="e-forgotpassword-wrap e-forgotpassword-cloth">
    <div class="container">
        <div class="row">
            <div class="col-12">                   
                <div class="e-fp-box">
                    <form action="{% url 'user:forget_pass' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                        
                              
                            <div class="col-md-12"> 

                            {{forget_pass_form}}
                        </div>
                            <div class="col-md-12">                                       
                                <div class="">
                                    <button class="e-btn" style="margin-top: 10px;"> ثبت رمز عبور جدید</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>        
            </div>           
        </div>
    </div>
</div>
{% endblock main %}

User/templates/User/forget_password.html
{% extends 'home.html' %}
{%load static %}

{% block main %}
<!-- Breadcumbs start -->
<div class="e-breadcumb-wrap text-center">
    <h2 class="e-breadcumb-title">ورود به حساب کاربری</h2>
    <ul class="e-breadcumb-kist">
        <li>
            <a href="{% url 'home' %}">خانه </a>
        </li>
        <li>
            <a href='{%static "javascript:void(0);" %}'> ورود به حساب کاربری</a>
        </li>
    </ul>
</div>
<!-- Product Category start -->
<div class="e-forgotpassword-wrap e-forgotpassword-cloth">
    <div class="container">
        <div class="row">
            <div class="col-12">                   
                <div class="e-fp-box">
                    <form action="{% url 'user:forget_password' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">                                        
                            {{forget_password_form}}
                        </div>
                            <div class="col-md-12">                                       
                                <div class="">
                                    <button class="e-btn" style="margin-top: 10px;"> بازیابی رمز عبور </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>        
            </div>           
        </div>
    </div>
</div>
{% endblock main %}

User/templates/User/forget_status.html
{% extends 'home.html' %}
{%load static %}

{% block main %}
<!-- Breadcumbs start -->
<div class="e-breadcumb-wrap text-center">
    <h2 class="e-breadcumb-title">ورود به حساب کاربری</h2>
    <ul class="e-breadcumb-kist">
        <li>
            <a href="{% url 'home' %}">خانه </a>
        </li>
        <li>
            <a href='{%static "javascript:void(0);" %}'> ورود به حساب کاربری</a>
        </li>
    </ul>
</div>
<!-- Product Category start -->
<div class="e-forgotpassword-wrap e-forgotpassword-cloth">
    <div class="container">
        <div class="row">
            <div class="col-12">                   
                <div class="e-fp-box">
                    <form action="{% url 'user:forget_pass' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                        
                            <h2>{{status}}</h2>
                            
                            <div class="col-md-12">                                       
                                
                            </div>
                        </div>
                    </form>
                </div>        
            </div>           
        </div>
    </div>
</div>
{% endblock main %}

User/templates/User/login.html
{% load static %}
<!-- The Modal -->
<div class="e-autho-model modal fade" id="login">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">        
        <!-- Modal body -->
        <div class="modal-body">
        <div class="modal-inner">
            <div class="row">
                <div class="col-md-12">
                    <div class="modal-inner-box">
                        <div class="autho-model-header text-center">
                            <a href="javascript:void(0);"><img src="assets/images/index1/big_logo.png" alt="logo" class="img-fluid"></a>
                            <p class="autho-model-sttl">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.</p>
                            <h2 class="autho-model-ttl">ورود </h2>
                        </div>
                        
                        <div class="autho-model-filed">
                            <form>
                                <div class="row">
                                    <div class="col-md-12">                                        
                                    {{login_form}}
                                </div>
                                    <div class="col-md-12">                                       
                                        <div class="e-form-field mb-20">
                                            <ul class="e-rememberforgot-list">
                                                <li>
                                                    <div class="e-checkbox-wrap">
                                                        <input class="e-checkbox-input" type="checkbox" id="remember_me">
                                                        <label for="remember_me" class="e-checkbox">مرا به خاطر بسپار </label>
                                                    </div>
                                                </li>
                                                <li><a href="forgot_password.html" class="e-comn-link">فراموشی رمز عبور؟ </a></li>
                                            </ul>                                            
                                        </div>
                                    </div> 
                                    <div class="col-md-12">                                       
                                        <div class="">
                                            <a href="index.html" class="e-btn">ورود </a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <button type="button" class="autho-close" data-dismiss="modal">&times;</button>
        </div>         
    </div>
    </div>
</div>

User/templates/User/login_page.html
{% extends 'home.html' %}

{% load static %}


{% block main %}
<!-- Breadcumbs start -->
<div class="e-breadcumb-wrap text-center">
    <h2 class="e-breadcumb-title">ورود به حساب کاربری</h2>
    <ul class="e-breadcumb-kist">
        <li>
            <a href="{% url 'home' %}">خانه </a>
        </li>
        <li>
            <a href='{%static "javascript:void(0);" %}'> ورود به حساب کاربری</a>
        </li>
    </ul>
</div>
<!-- Product Category start -->
<div class="e-forgotpassword-wrap e-forgotpassword-cloth">
    <div class="container">
        <div class="row">
            <div class="col-12">                   
                <div class="e-fp-box">
                    <form action="{% url 'user:login' %}?next={{next}}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">                                        
                            {{login_form}}
                        </div>
                            <div class="col-md-12">                                       
                                <div class="e-form-field mb-20">
                                    <ul class="e-rememberforgot-list">
                                        <li>
                                            <div class="e-checkbox-wrap">
                                                <input class="e-checkbox-input" type="checkbox" id="remember_me">
                                                <label for="remember_me" class="e-checkbox">مرا به خاطر بسپار </label>
                                            </div>
                                        </li>
                                        <li><a href="{% url 'User:forget_password' %}" >فراموشی رمز عبور؟ </a></li>
                                    </ul>                                            
                                </div>
                            </div> 
                            <div class="col-md-12">                                       
                                <div class="">
                                    <button class="e-btn" style="margin-top: 10px;"> ورود </a>
                                    
                                </div>
                                <p> <a href="{% url 'social:begin' 'github' %}">login with GitHub</a></p>
                            </div>
                        </div>
                    </form>
                </div>        
            </div>           
        </div>
    </div>
</div>
{% endblock main %}

User/templates/User/register.html
{% load static %}
<div class="e-autho-model modal fade" id="register">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">        
        <!-- Modal body -->
        <div class="modal-body">
        <div class="modal-inner">
            <div class="row">
                <!-- <div class="col-md-5">
                    left
                </div> -->
                <div class="col-md-12">
                    <div class="modal-inner-box">
                        <div class="autho-model-header text-center">
                            <a href="javascript:void(0);"><img src="assets/images/index1/big_logo.png" alt="logo" class="img-fluid"></a>
                            <p class="autho-model-sttl">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.</p>
                            <h2 class="autho-model-ttl">ثبت نام </h2>
                        </div>
                        
                        <div class="autho-model-filed">
                            

                            <form>
                                <div class="row">                                        
                                    <div class="col-md-12">                                       
                                        <div class="e-form-field mb-20">
                                            <label>نام </label>
                                            <input class="e-field-inner" type="text">
                                        </div>
                                    </div>
                                    <div class="col-md-12">                                       
                                        <div class="e-form-field mb-20">
                                            <label>ایمیل </label>
                                            <input class="e-field-inner" type="email">
                                        </div>
                                    </div>
                                    <div class="col-md-12">                                       
                                        <div class="e-form-field mb-20">
                                            <label>رمز عبور </label>
                                            <input class="e-field-inner" type="Password">
                                        </div>
                                    </div> 
                                    <div class="col-md-12">                                       
                                        <div class="">
                                            <a href="index.html" class="e-btn">ثبت نام </a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <button type="button" class="autho-close" data-dismiss="modal">&times;</button>
        </div>         
    </div>
    </div>
</div>